name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ devopslearnnits }}
        password: ${{ Nits@1280 }}

    - name: Build Docker Image
      run: docker build -t devopslearnnits/my-node-app .

    - name: Push Docker Image
      run: docker push devopslearnnits/my-node-app
